# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'About/Resume',   url: 'about.html'}
- {name: 'Projects', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}
- {name: 'Resume', url: 'Resume.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/magdalent'}
- {icon: 'linkedin',   link: 'https://ca.linkedin.com/in/magdalen-thot-2b4b7921a?trk=public_post-text'}
- {icon: 'envelope',   link: 'mailto:magdalenthot@hotmail.com'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'


post_date_prefix: 'Written on'

related_posts: 'Some Other Projects 𓆉'

